### ISSUE TITLE
Ajout d'un champ `start` dans l'objet `cfp`

### ISSUE THREAD

**Issue by welcoMattic** [saloonapp/saloon-backend#10]
Tout est dans le titre ;) 

Car avoir le lien du CFP ne signifie pas forcément qu'il soit ouvert

**Comment by welcoMattic** [comment]
Up ? ;)

**Comment by loicknuchel** [comment]
Salut,

En fait je l'ai mis au début mais voyant que c'est pas vraiment dispo comme info je l'ai enlevé...
C'est marqué nulle part sur le site ou le CFP et perso, je découvre presque jamais les CFPs avant qu'ils soient ouverts...
T'as vraiment ce use case d'être au courant de CFP alors qu'ils ne sont pas encore ouverts ?

**Comment by welcoMattic** [comment]
Salut Loïck,

En fait j'ai plutôt le use case d'avoir besoin de savoir quand le CFP démarre (pour une histoire de notification). C'est rare que le CFP soit en ligne sans être ouvert, mais ça arrive. Ce n'est absolument pas critique, je peux m'en passer ;)

Merci
